language: swift
xcode_project: CollapsibleTableHeaderView/CollapsibleTableHeaderView.xcodeproj
xcode_scheme: CollapsibleTableHeaderViewTests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPad Pro (9.7-inch)
osx_image: xcode10.2

